version: 2
updates:
  - package-ecosystem: "gradle"
    directory: "/"
    schedule:
      interval: daily
      time: "03:00"
    pull-request-branch-name:
      separator: "-"
    target-branch: main
    labels:
      - dependabot
    open-pull-requests-limit: 20
    commit-message:
      prefix: BAU
  - package-ecosystem: "github-actions"
    directory: "/"
    schedule:
      interval: "weekly"
    ignore:
      - dependency-name: "gradle/actions"
        # setup-gradle v6 contains updates to terms which we need to understand and review
        update-types: ["version-update:semver-major"]
    target-branch: main
    labels:
      - dependabot
    commit-message:
      prefix: BAU
