name: PR check

on:
  pull_request:
    branches: [ 'main' ]

jobs:

  pre-commit:
    runs-on: ubuntu-latest
    steps:
      - name: Pre-commit checks
        uses: govuk-one-login/github-actions/code-quality/run-pre-commit@3b0015c58dd0e19e1572fda59dda4184df387d1e
        with:
          all-files: true

  validate:
    runs-on: ubuntu-latest
    permissions:
      contents: read

    steps:
      - name: Checkout
        uses: actions/checkout@v6
        with:
          fetch-depth: 0

      - name: JDK setup
        uses: actions/setup-java@v5
        with:
          java-version-file: '.sdkmanrc'
          distribution: 'corretto'

      - name: Gradle setup
        uses: gradle/actions/setup-gradle@39e147cb9de83bb9910b8ef8bd7fff0ee20fcd6f
        with:
          cache-read-only: false

      - name: Checks and tests
        run: ./gradlew spotlessCheck unitTestCodeCoverageReport

      - name: Sonar analysis
        if: github.actor != 'dependabot[bot]'
        env:
          SONAR_TOKEN: ${{ secrets.SONAR_TOKEN }}
        run: ./gradlew sonar --info

      - name: Upload test report
        if: failure()
        uses: actions/upload-artifact@v6
        with:
          name: test-report
          path: build/reports/jacoco/
          retention-days: 3
